# 1. Tomcat Server Setting
server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.1.0.1:3306/smdb?characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    username: ENC(OAjB56HlNziHqNDu8ZFSAw==)
    password: ENC(zYoWFnp8CokAEj/HgST7Tw==)

# 3. Mybatis Setting
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 4. Logging Setting
logging:
  level:
    root: info
  #  error > info > debug

# 5. Application Environment Setting
app:
  dir:
    imgdir: file:///c:/springsm/imgs/
    # logdir: /root/users/project/logs
    logdir: file:///c:/springsm/logs/
    readlogdir: c:/springsm/logs/