# 1. Tomcat Server Setting
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    # 개발을 위해 사용
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    # 실제 사용을 할 때 사용
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.106.99.158:3306/smdb?characterEncoding=utf8
    username: smuser
    password: Smu1212!!

# 3. Mybatis Setting
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 4. Logging Setting
logging:
  level:
    root: info
    #  error > info > debug

# 5. Application Environment Setting
app:
  url:
    #server-url: http://175.106.99.158:81 # 네이버 서버 IP
    server-url: http://192.168.140.1:81 #내 IP
    #server-url: http://210.119.34.77:81 교수 IP
  dir:                                                                                                                                                                                                                                                 
    imgdir: /root/imgs/
    uploadimgdir: /root/imgs
    # logdir : /root/users/projects/logs/
    logdir: /root/logs/
    readlogdir: root/logs/
  key:
    wkey: ENC(sO0RYc9SsKzeZhlWAhVfG89pwzID8Vd2TIgr5nn6dZ7OtoSfTWvQjQx67xnwrV1H87FmDExorAqegiULCB7zrHbBYMZudzmj608UPokuxVsZZB0TW96Q5kuzxWHUjVAvueWEtW5VTLP200IjM2ZEeA==)
    sKey: ENC(uIR9MvAsqOBs/2d1WXXmm1ow2utOAICfWDxEvtCvPNzqQMpUnOqZjsa/Iz1IftUB)
    algo: ENC(46veWcF/jurbzJW253V8KAaiYfuqUXdK0TJZl8qncvw=)
    skey: ENC(XUGTCtIbo+egxzlX0lamkA==)